---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    application: logging
    component: logstash
data:
  logstash.yml: |
    http.host: 0.0.0.0
    node.name: ${HOSTNAME}
    path.config: /usr/share/logstash/config/conf.d
    xpack.monitoring.elasticsearch.password: changeme
    xpack.monitoring.elasticsearch.url: http://es-ingest:9200
    xpack.monitoring.elasticsearch.username: logstash_system
