---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: logging
        component: logstash
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: logstash
        imagePullPolicy: IfNotPresent
        image: docker.elastic.co/logstash/logstash:5.6.3
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 514
          name: syslog-tcp
          protocol: TCP
        - containerPort: 514
          name: syslog-udp
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: config-pipeline
          mountPath: /usr/share/logstash/config/conf.d
      volumes:
      - name: config
        configMap:
          name: logstash-config
      - name: config-pipeline
        configMap:
          name: logstash-config-pipeline
      restartPolicy: Always
